import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LightRays from "@/components/LightRays";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen bg-black text-white">
        <div aria-hidden="true" className="fixed inset-0 z-0 pointer-events-none">
          <LightRays
            raysOrigin="top-center"
            raysColor="#ffffff"
            raysSpeed={0.5}
            lightSpread={0.25}
            rayLength={5}
            followMouse={true}
            mouseInfluence={0.1}
            noiseAmount={0}
            distortion={0}
            pulsating={false}
            fadeDistance={1}
            saturation={1}
          />
        </div>

        <div className="relative z-10 min-h-screen">
          <main className="flex min-h-screen min-w-0 flex-1">
            {children}
          </main>

          <footer className="absolute inset-x-0 bottom-0 flex min-h-24 items-center justify-center gap-4 px-6 text-sm text-gray-400">
            <span>&copy; {new Date().getFullYear()} Mintbriq</span>
            <a
              href="https://github.com/lasjdhu/mintbriq"
              target="_blank"
              rel="noreferrer"
              className="transition hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white"
            >
              Source ↗
            </a>
          </footer>
        </div>
      </body>
    </html>
  );
}
